cp alexa_skill@2x.png alexa_skill.png
 cp check@2x.png check.png
 cp check_dark@2x.png check_dark.png
 cp google@2x.png google.png
 cp header@2x.png header.png
 cp header_dark@2x.png header_dark.png
 cp icon@2x.png icon.png
 cp intro_detail@2x.png intro_detail.png
 cp intro_home@2x.png intro_home.png
 cp intro_plan2@2x.png intro_plan2.png
 cp intro_plans@2x.png intro_plans.png
 cp intro_schedule@2x.png intro_schedule.png
 cp intro_share@2x.png intro_share.png
 cp months/april@2x.png months/april.png
 cp months/december@2x.png months/december.png
 cp months/february@2x.png months/february.png
 cp months/january@2x.png months/january.png
 cp months/jun@2x.png months/jun.png
 cp months/march@2x.png months/march.png
 cp months/may@2x.png months/may.png
 cp months/november@2x.png months/november.png
 cp months/october@2x.png months/october.png
 cp october@2x.png october.png 