---
language: node_js
node_js:
  - "12.6.0"

branches:
  only:
  - master

cache:
  directories:
    - ~/.npm

env:
  global:
    - YARN_VERSION="1.9.4"

jobs:
  include:
    - stage: test
      env:
        - YARN_CACHE_FOLDER="/home/travis/yarn_cache"
      cache:
        directories:
          - $HOME/yarn_cache
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
        - export PATH="$HOME/.yarn/bin:$PATH"
      before_script:
        - cd PeperomiaNative
      script:
        - yarn
        - yarn test
    - stage: lint
      env:
        - YARN_CACHE_FOLDER="/home/travis/yarn_cache"
      cache:
        directories:
          - $HOME/yarn_cache
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
        - export PATH="$HOME/.yarn/bin:$PATH"
      before_script:
        - cd PeperomiaNative
      script:
        - yarn
        - yarn eslint
#    - stage: deploy
#      env:
#        - YARN_CACHE_FOLDER="/home/travis/yarn_cache"
#      cache:
#        directories:
#          - $HOME/yarn_cache
#      before_install:
#        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
#        - export PATH="$HOME/.yarn/bin:$PATH"
#      before_script:
#        - cd PeperomiaNative
#      script:
#        - yarn
#        - yarn global add expo-cli
#        - expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
#        - expo publish --non-interactive
