# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "deploy testflight"
  lane :deploy_testflight do

    upload_to_testflight(
      username:  ENV["APPLE_ID"],
      app_identifier: "com.wheatandcat.peperomia",
      ipa: "ipa/peperomia.ipa",
      itc_provider: ENV["TEAM_ID"]
    )

  end
end
