// Code generated by MockGen. DO NOT EDIT.
// Source: domain/item_detail.go

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	firestore "cloud.google.com/go/firestore"
	context "context"
	gomock "github.com/golang/mock/gomock"
	domain "github.com/wheatandcat/Peperomia/backend/domain"
	reflect "reflect"
)

// MockItemDetailRepository is a mock of ItemDetailRepository interface
type MockItemDetailRepository struct {
	ctrl     *gomock.Controller
	recorder *MockItemDetailRepositoryMockRecorder
}

// MockItemDetailRepositoryMockRecorder is the mock recorder for MockItemDetailRepository
type MockItemDetailRepositoryMockRecorder struct {
	mock *MockItemDetailRepository
}

// NewMockItemDetailRepository creates a new mock instance
func NewMockItemDetailRepository(ctrl *gomock.Controller) *MockItemDetailRepository {
	mock := &MockItemDetailRepository{ctrl: ctrl}
	mock.recorder = &MockItemDetailRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockItemDetailRepository) EXPECT() *MockItemDetailRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockItemDetailRepository) Create(ctx context.Context, f *firestore.Client, i domain.ItemDetailRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, f, i)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockItemDetailRepositoryMockRecorder) Create(ctx, f, i interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockItemDetailRepository)(nil).Create), ctx, f, i)
}

// Update mocks base method
func (m *MockItemDetailRepository) Update(ctx context.Context, f *firestore.Client, i domain.ItemDetailRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, f, i)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockItemDetailRepositoryMockRecorder) Update(ctx, f, i interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockItemDetailRepository)(nil).Update), ctx, f, i)
}

// Delete mocks base method
func (m *MockItemDetailRepository) Delete(ctx context.Context, f *firestore.Client, i domain.ItemDetailRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, f, i)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockItemDetailRepositoryMockRecorder) Delete(ctx, f, i interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockItemDetailRepository)(nil).Delete), ctx, f, i)
}

// DeleteByUID mocks base method
func (m *MockItemDetailRepository) DeleteByUID(ctx context.Context, f *firestore.Client, uid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUID", ctx, f, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUID indicates an expected call of DeleteByUID
func (mr *MockItemDetailRepositoryMockRecorder) DeleteByUID(ctx, f, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUID", reflect.TypeOf((*MockItemDetailRepository)(nil).DeleteByUID), ctx, f, uid)
}
