# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc 'upload apk'
  lane :upload_apk do

    keyfile = "./fastlane/client_id.json"
    apk_file_path = "./apk/peperomia.apk"

    upload_to_play_store(
        package_name: "com.wheatandcat.peperomia",
        json_key: keyfile,
        track: "alpha",
        apk_paths: [apk_file_path]
      )
    end
end
