openapi: 3.0.0

servers:
  - url: http://localhost:8080
    description: Local server

info:
  version: 1.0.0
  title: ペペロミア API
  description: https://github.com/wheatandcat/Peperomia/tools//swagger.yaml

security:
  - bearerAuth: []   

paths:
  /CreateUser:
    post:
      tags:
        - 実装済み
      description: |
        - ユーザーを作成する
      responses:
        '201':
          description: |
            - 作成した
        '200':
          description: |
            - 既に作成済だった


  /SyncItems:
    post:
      tags:
        - 実装済み
      requestBody:
        $ref: '#/components/requestBodies/SyncItemsRequest'
      description: |
        - アプリの情報をバックアップする
      responses:
        '200':
          description: |
            - 同期成功した

  /LognWithAmazon:
    post:
      tags:
        - 実装済み
      requestBody:
        $ref: '#/components/requestBodies/AmazonWithLoginRequest'
      description: |
        - amazonアカウントとの連携情報を登録する
      responses:
        '200':
          description: |
            - 連携に成功した

  /amazon/RegisterItem:
    post:
      tags:
        - 未実装
      requestBody:
        $ref: '#/components/requestBodies/AlexaRegisterItemRequest'
      description: |
        - Alexa経由で予定を登録する
      responses:
        '200':
          description: |
            - 連携に成功した

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  requestBodies:
    SyncItemsRequest:
        description: アイテム同期のRequest
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
                  items:
                    $ref: '#/components/schemas/Item'

                itemDetails:
                  type: array
                  items:
                    $ref: '#/components/schemas/ItemDetail'
                calendars:
                  type: array
                  items:
                    $ref: '#/components/schemas/Calendar'
    AmazonWithLoginRequest:
        description: amazonアカウントに連携する
        content:
          application/json:
            schema:
              type: object
              properties:
                accessToken:
                  type: string
                  format: string
                  pattern: "qawaqwsedrftgyhujiko"
                  example: ""
                  description: アクセスToken
    AlexaRegisterItemRequest:
        description: Alexa経由で予定を登録Request
        content:
          application/json:
            schema:
              type: object
              properties:
                item:
                  $ref: '#/components/schemas/AlexaItem'

                itemDetails:
                  type: array
                  items:
                    $ref: '#/components/schemas/AlexaItemDetail'

  schemas:
    Item:
      type: object
      description: スケジュールアイテム
      properties:
        id:
          type: integer
          format: int32
          pattern: "1"
          example: 1
          description: ID
          required:
            - id
        title:
          type: string
          pattern: string
          example: 葛西臨海公園
          description: タイトル
        kind:
          type: string
          example: fishing
          description: アイコンの種類
        image:
          type: string
          example: ""
          description: 画像のBase64エンコード
        imagePath:
          type: string
          example: ""
          description: 画像のパス
    ItemDetail:
      type: object
      description: スケジュールアイテム詳細
      properties:
        id:
          type: integer
          format: int32
          pattern: "1"
          example: 1
          description: ID
        itemId:
          type: integer
          format: int32
          pattern: "1"
          example: 1
          description: アイテムID
        title:
          type: string
          pattern: string
          example: 葛西臨海公園
          description: タイトル
        kind:
          type: string
          example: fishing
          description: アイコンの種類
        memo:
          type: string
          example: ""
          description: メモ内容
        url:
          type: string
          example: ""
          description: リンク
        place:
          type: string
          example: ""
          description: 集合場所
        moveMinutes:
          type: integer
          pattern: "1"
          example: 30
          description: 移動時間（分）
        priority:
          type: integer
          pattern: "1"
          example: 1
          description: 表示順
    Calendar:
      type: object
      description: スケジュールアイテム日付
      properties:
        id:
          type: integer
          format: int32
          pattern: "1"
          example: 1
          description: ID
        itemId:
          type: integer
          format: int32
          pattern: "1"
          example: 1
          description: アイテムID
        date:
          type: string
          pattern: string
          example: "2018-01-01T00:00:00Z"
          description: 日付
    AlexaItem:
      type: object
      description: Alexa経由の予定
      properties:
        title:
          type: string
          pattern: string
          example: 葛西臨海公園
          description: タイトル
        date:
          type: string
          pattern: string
          example: "2018-01-01T00:00:00Z"
          description: 日付
    AlexaItemDetail:
      type: object
      description: Alexa経由の予定詳細
      properties:
        title:
          type: string
          pattern: string
          example: 葛西臨海公園
          description: タイトル