openapi: 3.0.0

servers:
  - url: http://localhost:8080
    description: Local server

info:
  version: 1.0.0
  title: ペペロミア API
  description: https://github.com/wheatandcat/Peperomia/tools//swagger.yaml

security:
  - bearerAuth: []   

paths:
  /CreateUser:
    post:
      tags:
        - 実装済み
      description: |
        - ユーザーを作成する
      responses:
        '201':
          description: |
            - 作成した
        '200':
          description: |
            - 既に作成済だった

  /CreateItem:
    post:
      tags:
        - 実装済み
      description: |
        - 予定を作成
      requestBody:
        $ref: '#/components/requestBodies/CreateItemRequest'
      responses:
        '201':
          description: |
            - 作成した
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'

  /UpdateItem:
    post:
      tags:
        - 実装済み
      description: |
        - 予定を更新
      requestBody:
        $ref: '#/components/requestBodies/UpdateItemRequest'
      responses:
        '200':
          description: |
            - 更新した


  /DeleteItem:
    post:
      tags:
        - 実装済み
      description: |
        - 予定を削除
        - 詳細な予定も削除
      requestBody:
        $ref: '#/components/requestBodies/DeleteItemRequest'
      responses:
        '200':
          description: |
            - 削除した


  /CreateItemDetail:
    post:
      tags:
        - 実装済み
      description: |
        - 予定詳細を作成
      requestBody:
        $ref: '#/components/requestBodies/CreateItemDetailRequest'
      responses:
        '201':
          description: |
            - 作成した
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemDetail'

  /UpdateItemDetail:
    post:
      tags:
        - 実装済み
      description: |
        - 予定詳細を更新
      requestBody:
        $ref: '#/components/requestBodies/UpdateItemDetailRequest'
      responses:
        '200':
          description: |
            - 更新した

  /DeleteItemDetail:
    post:
      tags:
        - 実装済み
      description: |
        - 予定詳細を削除
      requestBody:
        $ref: '#/components/requestBodies/DeleteItemDetailRequest'
      responses:
        '200':
          description: |
            - 削除した

  /CreateCalendar:
    post:
      tags:
        - 実装済み
      description: |
        - カレンダーを作成
      requestBody:
        $ref: '#/components/requestBodies/CreateCalendarRequest'
      responses:
        '201':
          description: |
            - 作成した
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Calendar'
  /UpdateCalendar:
    post:
      tags:
        - 実装済み
      description: |
        - カレンダーを更新
      requestBody:
        $ref: '#/components/requestBodies/UpdateCalendarRequest'
      responses:
        '200':
          description: |
            - 更新した

  /DeleteCalendar:
    post:
      tags:
        - 実装済み
      description: |
        - カレンダーを削除
      requestBody:
        $ref: '#/components/requestBodies/DeleteCalendarRequest'
      responses:
        '200':
          description: |
            - 削除した

  /SyncItems:
    post:
      tags:
        - 実装済み
      requestBody:
        $ref: '#/components/requestBodies/SyncItemsRequest'
      description: |
        - アプリの情報をバックアップする
      responses:
        '200':
          description: |
            - 同期成功した


  /LognWithAmazon:
    post:
      tags:
        - 実装済み
      requestBody:
        $ref: '#/components/requestBodies/AmazonWithLoginRequest'
      description: |
        - amazonアカウントとの連携情報を登録する
      responses:
        '200':
          description: |
            - 連携に成功した

  /amazon/RegisterItem:
    post:
      tags:
        - 実装済み
      requestBody:
        $ref: '#/components/requestBodies/AlexaRegisterItemRequest'
      description: |
        - Alexa経由で予定を登録する
      responses:
        '200':
          description: |
            - 連携に成功した

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  requestBodies:
    CreateItemRequest:
      description: 予定作成のRequest
      content:
        application/json:
          schema:
            type: object
            properties:
              item:
                $ref: '#/components/schemas/CraeteItem'

    UpdateItemRequest:
      description: 予定更新のRequest
      content:
        application/json:
          schema:
            type: object
            properties:
              item:
                $ref: '#/components/schemas/Item'

    DeleteItemRequest:
      description: 予定削除のRequest
      content:
        application/json:
          schema:
            type: object
            properties:
              item:
                $ref: '#/components/schemas/DeleteItem'

    CreateItemDetailRequest:
      description: 予定詳細作成のRequest
      content:
        application/json:
          schema:
            type: object
            properties:
              itemDetail:
                $ref: '#/components/schemas/CreateItemDetail'

    UpdateItemDetailRequest:
      description: 予定詳細更新のRequest
      content:
        application/json:
          schema:
            type: object
            properties:
              itemDetail:
                $ref: '#/components/schemas/ItemDetail'

    DeleteItemDetailRequest:
      description: 予定詳細削除のRequest
      content:
        application/json:
          schema:
            type: object
            properties:
              itemDetail:
                $ref: '#/components/schemas/DeleteItemDetail'

    CreateCalendarRequest:
      description: Calendar作成のRequest
      content:
        application/json:
          schema:
            type: object
            properties:
              calendar:
                $ref: '#/components/schemas/CraeteCalendar'

    UpdateCalendarRequest:
      description: Calendar更新のRequest
      content:
        application/json:
          schema:
            type: object
            properties:
              calendar:
                $ref: '#/components/schemas/Calendar'

    DeleteCalendarRequest:
      description: Calendar削除のRequest
      content:
        application/json:
          schema:
            type: object
            properties:
              calendar:
                $ref: '#/components/schemas/DeleteCalendar'


    SyncItemsRequest:
        description: アイテム同期のRequest
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
                  items:
                    $ref: '#/components/schemas/Item'

                itemDetails:
                  type: array
                  items:
                    $ref: '#/components/schemas/ItemDetail'
                calendars:
                  type: array
                  items:
                    $ref: '#/components/schemas/Calendar'

    AmazonWithLoginRequest:
        description: amazonアカウントに連携する
        content:
          application/json:
            schema:
              type: object
              properties:
                accessToken:
                  type: string
                  format: string
                  pattern: "qawaqwsedrftgyhujiko"
                  example: ""
                  description: アクセスToken

    AlexaRegisterItemRequest:
        description: Alexa経由で予定を登録Request
        content:
          application/json:
            schema:
              type: object
              properties:
                item:
                  $ref: '#/components/schemas/AlexaItem'

                itemDetails:
                  type: array
                  items:
                    $ref: '#/components/schemas/AlexaItemDetail'

  schemas:
    CraeteItem:
      type: object
      description: スケジュールアイテム
      properties:
        title:
          type: string
          pattern: string
          example: 葛西臨海公園
          description: タイトル
        kind:
          type: string
          example: fishing
          description: アイコンの種類

    Item:
      type: object
      description: スケジュールアイテム
      properties:
        id:
          type: string
          pattern: string
          example: "1"
          description: ID
          required:
            - id
        title:
          type: string
          pattern: string
          example: 葛西臨海公園
          description: タイトル
        kind:
          type: string
          example: fishing
          description: アイコンの種類

    DeleteItem:
      type: object
      description: スケジュールアイテム
      properties:
        id:
          type: string
          pattern: string
          example: "1"
          description: ID
          required:
            - id

    CreateItemDetail:
      type: object
      description: スケジュールアイテム詳細
      properties:
        itemId:
          type: string
          pattern: string
          example: "1"
          description: アイテムID
        title:
          type: string
          pattern: string
          example: 葛西臨海公園
          description: タイトル
        kind:
          type: string
          example: fishing
          description: アイコンの種類
        memo:
          type: string
          example: ""
          description: メモ内容
        url:
          type: string
          example: ""
          description: リンク
        place:
          type: string
          example: ""
          description: 集合場所
        moveMinutes:
          type: integer
          pattern: "1"
          example: 30
          description: 移動時間（分）
        priority:
          type: integer
          pattern: "1"
          example: 1
          description: 表示順

    ItemDetail:
      type: object
      description: スケジュールアイテム詳細
      properties:
        id:
          type: string
          pattern: string
          example: "1"
          description: ID
        itemId:
          type: string
          pattern: string
          example: "1"
          description: アイテムID
        title:
          type: string
          pattern: string
          example: 葛西臨海公園
          description: タイトル
        kind:
          type: string
          example: fishing
          description: アイコンの種類
        memo:
          type: string
          example: ""
          description: メモ内容
        url:
          type: string
          example: ""
          description: リンク
        place:
          type: string
          example: ""
          description: 集合場所
        moveMinutes:
          type: integer
          pattern: "1"
          example: 30
          description: 移動時間（分）
        priority:
          type: integer
          pattern: "1"
          example: 1
          description: 表示順
          
    DeleteItemDetail:
      type: object
      description: スケジュールアイテム詳細
      properties:
        id:
          type: string
          pattern: string
          example: "1"
          description: ID
          required:
            - id

    CraeteCalendar:
      type: object
      description: スケジュールアイテム日付
      properties:
        itemId:
          type: string
          pattern: string
          example: "1"
          description: アイテムID
        date:
          type: string
          pattern: string
          example: "2018-01-01T00:00:00Z"
          description: 日付
          
    Calendar:
      type: object
      description: スケジュールアイテム日付
      properties:
        id:
          type: string
          pattern: string
          example: "1"
          description: ID
        itemId:
          type: string
          pattern: string
          example: "1"
          description: アイテムID
        date:
          type: string
          pattern: string
          example: "2018-01-01T00:00:00Z"
          description: 日付

    DeleteCalendar:
      type: object
      description: スケジュールアイテム日付
      properties:
        id:
          type: string
          pattern: string
          example: "1"
          description: ID

    AlexaItem:
      type: object
      description: Alexa経由の予定
      properties:
        title:
          type: string
          pattern: string
          example: 葛西臨海公園
          description: タイトル
        date:
          type: string
          pattern: string
          example: "2018-01-01T00:00:00Z"
          description: 日付
    AlexaItemDetail:
      type: object
      description: Alexa経由の予定詳細
      properties:
        title:
          type: string
          pattern: string
          example: 葛西臨海公園
          description: タイトル