name: jest
on: [push]

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache node_modules PeperomiaNative
      uses: actions/cache@preview
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-PeperomiaNative-${{ hashFiles(format('{0}{1}', github.workspace, '/PeperomiaNative/yarn.lock')) }}
        restore-keys:
          ${{ runner.os }}-PeperomiaNative-
    - name: Install node_modules primitive
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install
      working-directory: ./primitive
    - name: tsc primitive
      run: yarn tsc
      working-directory: ./primitive
    - name: Install node_modules PeperomiaNative
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install
      working-directory: ./PeperomiaNative
    - name: copy app.json
      run: cp -r app.test.json app.json
      working-directory: ./PeperomiaNative
    - name: test coverage
      run: yarn test:coverage
      working-directory: ./PeperomiaNative
    - name: codecov
      run: yarn codecov
      working-directory: ./PeperomiaNative
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}