name: jest
on: [push]

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache node_modules Peperomia
      uses: actions/cache@preview
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-Peperomia-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
        restore-keys:
          ${{ runner.os }}-Peperomia-
    - name: Install node_modules Peperomia
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install
    - name: copy app.json
      run: cp -r app.test.json app.json
    - name: test coverage
      run: yarn test:coverage
    - name: codecov
      run: yarn codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}