name: lint
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache node_modules PeperomiaNative
      uses: actions/cache@preview
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-PeperomiaNative-${{ hashFiles(format('{0}{1}', github.workspace, '/PeperomiaNative/yarn.lock')) }}
        restore-keys:
          ${{ runner.os }}-PeperomiaNative-
    - name: Install node_modules PeperomiaNative
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn install
      working-directory: ./PeperomiaNative
    - name: lint
      run: yarn eslint
      working-directory: ./PeperomiaNative
